### ISSUE TITLE
Validation Issue not Showing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1026]
In this screenshot:

![image](https://user-images.githubusercontent.com/535300/72364133-d4c14e80-36aa-11ea-822e-7889cfa1a11f.png)

You can see that the id formatting is wrong, but the footer warnings shows all green. Can we make it so these issues surface in the validator panel?

**Comment by chipit24** [comment]
Currently, errors are displayed for BPMNLint, and there's no integration with the form renderer errors. The easiest solution would be to mirror the form errors in our bpmnlint rules. However, we're not aware of all the renderer errors that could be displayed in the inspector panel, and as soon as they change they would become out of sync with the bpmnlint rules.

Our proposed solution is to emit errors from vue-form-renderer, and listen to those errors in modeler. This would require two PRs: one in modeler, and one in screen-builder.

Currently, the screen-builder does not emit a list of errors for its form controls; adding this feature could take 2 days, and integrating with modeler another day.

@velkymx Let us know if you want us to move forward with that.

**Comment by chipit24** [comment]
Looks like a warning is shown for the missing ID when the process is saved or loaded:
<img width="731" alt="Screen Shot 2020-02-03 at 1 34 21 PM" src="https://user-images.githubusercontent.com/7561061/73680249-f0a48880-4689-11ea-8056-79e7c139b3dd.png">

Adding an error on top of that might be confusing for users, as they would see an error and a warning for the same issue.

**Comment by chipit24** [comment]
Current proposition: Look into emitting errors from `vue-form-renderer`, catch them in modeler, and display them in the validation footer.

**Comment by chipit24** [comment]
> Current proposition: Look into emitting errors from `vue-form-renderer`, catch them in modeler, and display them in the validation footer.

Digging into this further, this seems like it's going to require significant work and still not be an ideal solution.

For errors in form elements to show up in modeler's validation footer, changes will be required across modeler, processmaker core, screen-builder, and vue-form-elements:
 * Errors need to propagate up from form elements, then be collected and emitted from screen-builder. 
 * At that point, they will need to be listened for in modeler and passed up to `ModelerApp` (which PM core has its own version of) to finally be displayed.
 * These errors are not associated with any specific element, so the error data will need to be mutated to inject information that will allow associating specific errors with specific elements in modeler.
 * And finally, the inspector panel is re-rendered for each element which is highlighted, so there's currently no way to persist and keep track of which errors are valid and which elements currently have errors caused by some form element.

With all this in mind, I think the best solution would be the one that came to mind first:
> Currently, errors are displayed for BPMNLint, and there's no integration with the form renderer errors. The easiest solution would be to mirror the form errors in our bpmnlint rules.
