### ISSUE TITLE
Alert Variant: Warning

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#1095]
On the loading dialogue - we should use the WARNING variant of the alert. Right now we have some type of custom CSS.

![image](https://user-images.githubusercontent.com/535300/73987334-dcb08f00-48f4-11ea-8f04-78f8f8ca4a29.png)

**Comment by chipit24** [comment]
@velkymx Can you please clarify what you mean by "some type of custom CSS".

That loading alert is currently triggered through the PM alert function:
https://github.com/ProcessMaker/modeler/blob/81ab6700ae8ae9baa5f137380d8f7f0996e13610/src/components/modeler/Modeler.vue#L187

No custom CSS was used; it's using the "info" dialog variant as I thought that was the most appropriate at the time, since it's providing info to the user, not necessarily highlighting a warning or error that has occurred.

If my assumptions are correct, then fixing this is as easy as replacing the string `'info'` with `'warning'` in the line of code above. Let me know if this is what you were thinking. Also, your screenshot includes "The process was saved" alert, but I'm not sure how that relates to this.
___

On an unrelated note, I've removed the `bug` label from this issue and added a new label: `defect`. The bug label had the description of "something isn't worked"; in this case, the dialog is clearly working, there was simply a miscommunication about the requirements for the colour of the alert.

<img width="551" alt="Screen Shot 2020-02-07 at 2 24 33 PM" src="https://user-images.githubusercontent.com/7561061/74059218-996a2500-49b5-11ea-8db9-334d99a4533d.png">

<img width="529" alt="Screen Shot 2020-02-07 at 2 24 40 PM" src="https://user-images.githubusercontent.com/7561061/74059236-a129c980-49b5-11ea-9f01-71b9e0acae71.png">

The lines are a bit blurred in some cases but it helps us distinguish and prioritize issues.
