### ISSUE TITLE
Sequence Flows Go Through Elements

### ISSUE THREAD

**Issue by vehikl-morning-mob** [ProcessMaker/modeler#183]
![image](https://user-images.githubusercontent.com/39924126/52088371-aa4db280-2579-11e9-9c87-8ff87695b440.png)

**Comment by chipit24** [comment]
Quirks with sequence flows exist even in Camunda:
<img width="605" alt="screen shot 2019-02-01 at 10 18 03 am" src="https://user-images.githubusercontent.com/7561061/52142977-55b54080-2628-11e9-8582-031663356710.png">
There is a bit of tweaking that can be done with jointjs, but there will always be edge cases when sequence flows don't look quite right. E.g. I updated the router to help prevent overlapping, but it still falls apart when elements are very close:
<img width="244" alt="screen shot 2019-02-01 at 1 53 51 pm" src="https://user-images.githubusercontent.com/7561061/52143244-f60b6500-2628-11e9-98b6-6900f27454b2.png">
<img width="216" alt="screen shot 2019-02-01 at 1 54 07 pm" src="https://user-images.githubusercontent.com/7561061/52143249-f86dbf00-2628-11e9-9b10-3f0ba3e24bd4.png">

A complete solution may require setting up a custom router, anchors, and connectPoints, as well as precisely defining what the problem is (how flows should appear in all cases). This requires more discussion.

**Comment by velkymx** [comment]
We're most concerned about the overlapping lines, especially from gateways. Make the flow confusing.
