### ISSUE TITLE
Subprocess Marker

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#260]
![screenshot 2019-02-26 08 22 59](https://user-images.githubusercontent.com/535300/53428529-d05f4a80-399f-11e9-8d20-5a07b7fc1f13.png)

https://docs.camunda.org/manual/7.6/reference/bpmn20/subprocesses/call-activity/

Inspector should allow for selected another process that is active.

**Comment by chipit24** [comment]
From the BPMN spec:
<img width="816" alt="screen shot 2019-02-28 at 3 36 13 pm" src="https://user-images.githubusercontent.com/7561061/53596797-9db77c80-3b6e-11e9-9ef1-8f727c16df61.png">

Currently, we do not have global tasks. I have two questions:
* What should happen when you create a call activity but there is only one process (the main process)?
* Should it be possible to assign the `calledElement` property to the call activitie's parent/containing process?

**Comment by caleeli** [comment]
Yes it is possible to call to the same parent/containing process, that workflow pattern is named Recursion (wcp22) and its availability depends on the Product implementation. Ex:

Product/Language | Version | Score | Motivation
-- | -- | -- | --
Staffware | 10 | + | Using the dynamic subprocedure step it is possible to call any procedure. However, it is unclear whether this is inadvertant rather than intended behaviour (i.e. a backdoor).
Websphere MQ | 3.4 | + | Directly supported. Recursive definition of process and block activities is possible.
FLOWer | 3.51 | - | Not supported.
COSA | 5.1 | + | Recursive definition of process models can be achieved using triggers or the activ_run tool agent.
iPlanet | 3.0 | + | Supported via synchronous subprocess activities.
SAP Workflow | 4.6c | + | A "multistep task" (i.e. an activity that is decomposed into a sub-workflow) contains a reference to a workflow definition hence a workflow could be decomposed into itself.
FileNet | 3.5 | - | Not supported.
BPEL | 1.1 | - | Not supported. Recursive composition is possible on an external basis using the <invoke> construct against web services but there is no internal support.
Websphere Integration Developer | 6.0 | - | Not supported. Recursive composition is possible on an external basis using the <invoke> construct against web services but there is no internal support.
Oracle BPEL | 10.1.2 | - | Not supported. Recursive composition is possible on an external basis using the <invoke> construct against web services but there is no internal support.
BPMN | 1.0 | - | Not supported. No means of specifying recursive composition with a process model.
XPDL | 2.0 | - | Not supported. No means of specifying recursive composition with a process model.
UML ADs | 2.0 | - | Not supported. No means of specifying recursive composition with a process model.
EPC (implemented by ARIS toolset 6.2) | - | Not supported.
jBPM | 3.1.4 | - | jBPM does not support recursion.
OpenWFE | 1.7.3 | + | OpenWFE supports recursion through the invocation of a sub-processes, which can recursively invoke itself.
Enhydra Shark | 2 | + | Enhydra Shark supports recursion. A workflow can invoke itself by means of subflow.

Actually Nayra should be able to support this kind of Recursion.

**Comment by chipit24** [comment]
> you need to add unit tests to verify it

@caleeli How would I do this? Aside from correctly setting the `calledElement` property, there's nothing else to verify on the front-end/modeler, right?

**Comment by caleeli** [comment]
Oh, I'm sorry, I meant to say that I should add unit test in Nayra to verify the Recursion pattern. Nothing really in the front-end.

**Comment by chipit24** [comment]
Ok, thanks for clarifying the recursion and testing!

**Comment by velkymx** [comment]
Remove the option for global tasks.
