### ISSUE TITLE
Add support for modifying inspector configurations for elements

### ISSUE THREAD

**Issue by tdondich** [ProcessMaker/modeler#30]
As a developer integrating modeler into other systems (such as ProcessMaker BPM), I need to be able to extend/replace the inspector configuration for elements so I can add better integration into the target platform.

Use Case: In ProcessMaker BPM, there are concepts of screens which are customized input screens designed by vue-form-builder. For user tasks in BPM, we need to be able to assign a specified screen to a user task.  This is stored in the XML as the screenRef attribute, but in the inspector for the task, I should be able to specify it using a custom visual inspector configuration component.

**Comment by caleeli** [comment]
To bring this support, the following methods were implemented:

- **registerInspectorExtension**: Register an inspector component to configure extended attributes and elements for specific bpmn extensions and execution environments. 
- **registerBpmnExtension**: Register a BPMN Moddle extension in order to support extensions to the bpmn xml format. This is used to support new attributes and elements that would be needed for specific BPMN implementations.
- **registerNode**: This registers a node component to use in the BPMN modeler. The components controls the rendering of a BPMN element.
