### ISSUE TITLE
Text Annotation - bpm definition is not valid

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#441]
![image](https://user-images.githubusercontent.com/535300/59864958-bd9cc700-933c-11e9-8f52-0daff8102d7a.png)

Immediately prior to placing the Text Annotation element, I saved the Process model successfully.

However, after placing the Text Annotation element as you see in the screenshot and then trying to save I receive a "The bpm definition is not valid" error. Is this valid or a bug? I do have Auto-validate enabled and I see no problems.

**Comment by tuantruong625** [comment]
@velkymx 
I'm not getting the ` bpm definition is not valid` when I save a text annotation. Fixed in the latest develop. 

I get a different bug of `Element instance for id "node_3` was not found` when I move the text annotation into a different lane or add a new lane. 

**Video of Bug in Spark**
https://drive.google.com/open?id=1AQYuAWhNDi3SmfDP7PCEOGeNzj1VVlcQ
