### ISSUE TITLE
Microsoft Edge Inspector

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#495]
![image](https://user-images.githubusercontent.com/535300/61983630-fe2fd600-afb5-11e9-87c2-9f9f7e27ed58.png)

Process Modeler: Can't scroll all the way to bottom of page in Microsoft Edge

**Comment by chipit24** [comment]
Tested this on Edge 18 on Windows 10 (in BrowserStack) and the issue seems to have been resolved:
<img width="838" alt="Screen Shot 2019-08-01 at 12 35 07 PM" src="https://user-images.githubusercontent.com/7561061/62311062-ec887b80-b458-11e9-91b6-51f92e8bdeb3.png">

May have been fixed as part of https://github.com/ProcessMaker/processmaker/pull/2202. Closing this issue.
