### ISSUE TITLE
Slow Loads / Optimizations

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#503]
When rendering this process (attached) the whole modeler becomes unresponsive and the browser starts using lots of CPU cycles. We need to find ways to optimize for larger processes so this isn't an issue going forward. 

[total_accounts_payable_w_f.json.txt](https://github.com/ProcessMaker/modeler/files/3469350/total_accounts_payable_w_f.json.txt)

![image](https://user-images.githubusercontent.com/535300/62493652-7b153980-b786-11e9-9e9c-d1a2de48cd68.png)

Profile of the process:

![image](https://user-images.githubusercontent.com/535300/62493856-f840ae80-b786-11e9-984f-598542442ce9.png)

**Comment by velkymx** [comment]
Maybe offload the configureCrown / configurePool until after load?

![image](https://user-images.githubusercontent.com/535300/62494360-2d99cc00-b788-11e9-8245-6bc55994773e.png)

**Comment by chipit24** [comment]
I've identified two main problems when it comes to performance.

1. During **parsing** (on initial load and after each undo or redo action), each node in the XML is added to the JointJS paper/grid _one by one_. For the process attached to this ticket, that means about 122 calls to `this.shape.addTo(this.graph)` are made, and each call results in JointJS attempting to re-render it's view.

2. After the initial render, interacting with the process causes it to hang as well. This is caused by a call to `setShapeStacking` in `Modeler.vue`. This function is called to ensure elements do not overlap in unexpected ways (for example, to prevent sequence flows from disappearing behind pools or lanes).

The calls to configure the crown elements and configure the pool can be deferred, however, the performance gain here is negligible. The big issues are the two described above. Possible solutions to the problems, respectively, are:

1. Use async rendering in JointJS: https://resources.jointjs.com/docs/jointjs/v2.2/joint.html#dia.Paper.prototype.options.async. This would allow batching all calls to add cells, so instead of JointJS attempting 122 re-renders, it only does one render. On initial implementation, this appears to fix the long load time on initial render, but introduces some problems as elements were created with the assumption that they would be synchronously rendered.

2. Upgrading to JointJS 3 and wrapping the call to `setShapeStacking` in `paper.freeze` and `paper.unfreeze`: https://resources.jointjs.com/docs/jointjs/v3.0/joint.html#dia.Paper.prototype.freeze. JointJS 3 introduced new optimizations to async rendering, including the ability to manually freeze and unfreeze rendering. This greatly simplifies the logic required to fix the two major optimization issues, but requires a thorough re-test of the application to ensure parts of the code that relied on JointJS 2 are still working as expected.

**Comment by chipit24** [comment]
Here is a link to a video showing the improved speed of loading the process attached in this ticket: https://www.dropbox.com/s/dz6r8l4jqvsar2t/loading_large_process.mov?dl=0.

**Comment by velkymx** [comment]
Can we get an estimate of work to upgrade to JointJS 3?

**Comment by chipit24** [comment]
@velkymx 

Some issues I've noticed when updating to async rendering and JointJS 3:

1. Undo/redo is broken (shapes completely disappear instead of their properties being set back to previous value).
2. Text annotation doesn't render.
3. Loading a large process after one has already been loaded causes sequence flows to break (they are no longer connected to the proper source element and instead point to the top left of the grid).

Some notable / relevant changes in JointJS 3:
* dia.Paper - add freeze(), unfreeze(), isFrozen() and option `frozen` to stop/start views updates
* dia.CellView - listening for underlying model changes switched from a specific attribute change (e.g. `change:size`) to a general `change` event [breaking change]
* dia.Paper - async mode revamped (viewport matching, rendering progress) [breaking change]

The above issues aren't clear-cut and may take a whole day, at best, to resolve each one. Issue #3 could be put on the backburner as a process is only loaded once, whereas in standalone it's possible to upload any number of XML or BPMN files once the app has loaded.

Changing to async rendering and upgrading to JointJS 3 is a big step, and I'd give it a solid week to iron out the above problems.

**Comment by chipit24** [comment]
To reduce the risk of upgrading to JointJS 3 and fixing optimizations at the same time, and to help track progress, we've broken out the JointJS 3 upgrade into a separate issue: https://github.com/ProcessMaker/modeler/issues/526.
