### ISSUE TITLE
Duplicated ID issue

### ISSUE THREAD

**Issue by caleeli** [ProcessMaker/modeler#641]
Issue: User can not create and save a flow from the start event to the Before Dynaform Script.

![image](https://user-images.githubusercontent.com/8028650/64973456-0cdd8f80-d879-11e9-9f56-104d45993565.png)

When saved he gets the following error:
![image](https://user-images.githubusercontent.com/8028650/64973501-24b51380-d879-11e9-8911-45e5ee69d546.png)

This is caused because a duplicated ID: **node_17_di**
assigned to the created flow (<bpmndi:BPMNEdge>).

Attached the BPMN source of the process: 

[bugProcess.bpmn](https://github.com/ProcessMaker/modeler/files/3617104/bugProcess.bpmn.txt)

**Comment by mc-ivan** [comment]
Great! That was my process issue.

**Comment by JCook21** [comment]
@caleeli @mc-ivan I've just imported this into the standalone modeler without any issues. I also checked the XML of the file you added to the issue and I can only see the node id 'node_17_di' appearing once. Can you give us a bit more information on how this file was arrived at? Is it exported from another system or was it created in the process maker app? From what I'm seeing right now with the information you've provided this is not a problem with the modeler component.

For the future, and to avoid going back and forth like this, can you add the following sections to all bug reports:
- Description
- Full steps to reproduce
- Expected behaviour
- Actual behaviour

**Comment by JCook21** [comment]
<img width="1677" alt="Screen Shot 2019-09-19 at 9 51 20 AM" src="https://user-images.githubusercontent.com/858371/65250717-01ca6f80-dac4-11e9-89c4-e288c00479bd.png">

Here's a screenshot of what I see when importing the attached file into the modeler. The file renders correctly, I'm able to download and re-upload the XML from it with no issues.
