### ISSUE TITLE
Import Error: elementDescriptor.isGeneric

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#757]
# Bug report issue
## Description
Interacting with the lane causes the BPMN file to become invalid and throw:

There was an error saving: TypeError: undefined is not an object (evaluating 'elementDescriptor.isGeneric')

## Reproduction steps

Import the BPMN file:
https://www.dropbox.com/s/m72k4b472k67aqy/SP.08.DSS02.01%20Correspondence%20with%20Customer%20%28en%29.bpmn?dl=0

Click and move the top lane. 

Try and save.

Video of the issue:
https://www.dropbox.com/s/g3uz01igr8272my/Screen%20Recording%202019-10-22%20at%208.05.25%20AM.mov?dl=0

Related to the import at #756

**Comment by chipit24** [comment]
I didn't see this error when looking into https://github.com/ProcessMaker/modeler/issues/756. There is no reference to `elementDescriptor` or `isGeneric` on the modeler; I can only assume the error was thrown from the JointJS code.

Without a stack trace, reproduction steps, verions used, etc., this error gives me no information.

**Comment by JCook21** [comment]
@velkymx could you please take the issue template we created and fill it out for this issue? Without all of the information that template requests, including complete reproduction steps, we're just wasting a lot of time going backwards and forwards trying to guess how to reproduce this.

**Comment by velkymx** [comment]
https://www.dropbox.com/s/g3uz01igr8272my/Screen%20Recording%202019-10-22%20at%208.05.25%20AM.mov?dl=0

**Comment by velkymx** [comment]
This is using the same import into the development server.

**Comment by chipit24** [comment]
@velkymx This issue comes from `bpmn-moddle` throwing an error when it comes across `documentation` and `extensionElement` elements in the XML document. Though these are both valid BPMN elements, `bpmn-moddle` seems unable to correctly parse them.

If we remove all `documentation` and `extensionElement` nodes from the _SP.08.DSS02.01 Correspondence with Customer (en).bpmn_ file, we no longer receive the "isGeneric" error, and we're able to successfully save and re-load the process.

A permanent fix may require opening an issue with `bpmn-moddle`, but for now, we can do one of two things:
 1. Create a blacklist of components that we remove from the XML when parsing it.
 2. Create a whitelist of components we support, and remove all other elements when parsing the XML.

No. 1 above may be the quickest, while no. 2 will protect us from potential issues in the future if we come across another element that modeler or one of its dependencies doesn't support.

**Comment by velkymx** [comment]
I like the idea of the whitelist. I think it's a more solid fix.

**Comment by tdondich** [comment]
Camunda modeler uses bpmn moddle and it has no such problem.  Can we
investigate how they are approaching this?  The bpmn file imports with no
issues with that tool.

**Comment by JCook21** [comment]
@tdondich yes we can. We are planning on looking further into this once we have a fix in place for this issue.
