### ISSUE TITLE
Duplicated ID issue

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#774]
# Bug report issue
## Description
When updating the provided bpmn in a certain way, it duplicates node_17_di.
https://github.com/ProcessMaker/modeler/files/3617104/bugProcess.bpmn.txt
## Reproduction steps
You must upload the provided bpmn and then edit it from this:
![Screen Shot 2019-10-30 at 10 20 14 AM](https://user-images.githubusercontent.com/6653340/67866184-ed37b900-fafe-11e9-93c8-50e25052c493.png)
to this:
![Screen Shot 2019-10-30 at 10 33 28 AM](https://user-images.githubusercontent.com/6653340/67867408-bf537400-fb00-11e9-8ff3-eb88ae66a3d7.png)

The Sequence Flow is changed from **Report Expense** to **Before Dynaform**

Then it does duplicate **node_17_di** in the xml.
## Expected behaviour
Change the Start Sequence Flow to **Before Dynaform** and it should not duplicate **node_17_di**
## Actual behaviour
**node_17_di** is duplicated when the sequence flow is changed from **Report Expense** to **Before Dynaform**
## Software used
Latest Chrome. Modeler v 0.17.5.

**Comment by lisa-fehr** [comment]
Original:
```
<bpmndi:BPMNShape id="node_17_di" bpmnElement="node_10">
        <dc:Bounds x="560" y="530" width="116" height="76" />
      </bpmndi:BPMNShape>
```
After change it adds:
```      
      <bpmndi:BPMNEdge id="node_17_di" bpmnElement="node_17">
        <di:waypoint x="148" y="148" />
        <di:waypoint x="258" y="8" />
      </bpmndi:BPMNEdge>
```


----
```
<bpmndi:BPMNShape id="node_17_di" bpmnElement="node_10">
        <dc:Bounds x="560" y="530" width="116" height="76" />
      </bpmndi:BPMNShape>
```
If removed, node_10 disappears. node_10 is **Reimburse**. 
![Screen Shot 2019-10-31 at 11 05 29 AM](https://user-images.githubusercontent.com/6653340/67958961-618d5d80-fbce-11e9-9bb8-371638ab9917.png)

The file has several BPMNEdges that have ids which don't match the bpmnElement.
**If the BPMNEdge ids are changed to match the bpmnElement, it fixes the problem.**

**Comment by lisa-fehr** [comment]
I notice I can save it regardless of the error. But it doesn't fix how invalid the diagram is becoming.

**Comment by chipit24** [comment]
The issue is as @lisa-fehr described. While node IDs are unique, there's no such constraint or check on diagram IDs. The bug can be reproduced with a simpler diagram: https://www.dropbox.com/s/ped176tf8x9wun4/test.xml?dl=0.

That diagram contains a task with ID `node_2` but with diagram ID `node_1_di`. When you drag another element onto the grid after uploading that XML, it will receive an ID of `node_1` and a diagram ID of `node_1_di`. The process now contains two shapes with the same diagram ID of `node_1_di`.

I'm not sure what the best solution for this would be, or if this is something we should focus on for this sprint. Let's discuss this during standup tomorrow. One possible solution:

 * Update `node.diagram.id` to be `${node.definition.id}_di` when the XML is parsed, ensuring that IDs match; and update the diagram ID when the node ID changes.

**Comment by chipit24** [comment]
We can go ahead with the above solution.
