### ISSUE TITLE
Move Secondary Nav Buttons

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#788]
![image](https://user-images.githubusercontent.com/535300/68328056-61d0a180-0083-11ea-93e8-93bc927c30fe.png)

**Comment by velkymx** [comment]
Undo redo icons (move text to tooltip):

https://fontawesome.com/icons/step-backward?style=solid
https://fontawesome.com/icons/step-forward?style=solid

**Comment by chipit24** [comment]
Use negative margins to position the toolbar above the designer.

**Comment by JCook21** [comment]
@velkymx we have a few concerns about moving these nav buttons outside of the modeler area and we have a couple of alternative proposals to share. These are the concerns we have:

- Without significant refactoring we would need to use negative margins to position the toolbar outside of the modeler component. This feel sub optimal to us and we're worried that this might be brittle due to browser differences.
- If we still wanted to place the panel in this location but didn't want to use negative margins to position it we would need to make significant changes to both the modeler and core to enable this.
- The proposed location of the toolbar is also used for other text. We are concerned that there could be some issues with overlap, etc.
- We do feel that there could be some problems with UX by moving these buttons outside of the main modeler. We feel it would be a little more natural to keep all of the controls for manipulating the modeler inside the modeler.

We have two alternative proposals: making the nav buttons part of the left hand controls panel or moving the controls into the footer. Both of these would keep the buttons in the main modeler but would free up the space they currently use in the diagram as a whole. We have two mockups showing these which you can view at https://www.figma.com/proto/c8UF9H198ETlQiLZyqvH4O/modeler-toolbar?node-id=1%3A24916&viewport=405%2C472%2C0.43839046359062195&scaling=min-zoom and https://www.figma.com/file/2G82qmL6DnjbYg94yixiiU/modeler-toolbar-footer?node-id=0%3A1.

Let's discuss this in person when you're back and see what the best way forwards is.

**Comment by chipit24** [comment]
The solution discussed involves:
 * Adding a callback function the the `modeler-start` event that would allow adding the breadcrumb link target and process name.
 * Modifying the modeler blade template (https://github.com/ProcessMaker/processmaker/blob/develop/resources/views/processes/modeler/index.blade.php) to pass the link target and process name to modeler via the `modeler-start` event listener.
   * Remove the breadcrumbs bar from the blade template.
   * Add the breadcrumbs bar to the modeler.
   * The save button that is also part of the breadcrumbs toolbar will also be moved into the modeler, and the code for it can be simplified.
   * The breadcrumbs and save button should not display in standalone.
