### ISSUE TITLE
Move computed properties onto the Node

### ISSUE THREAD

**Issue by lisa-fehr** [ProcessMaker/modeler#840]
crownConfig.vue has computed properties that could be placed on the Node saved to the store.

Nodes are added to the store in Modeler.vue@addNode

**Comment by chipit24** [comment]
Currently, nodes are plain objects:
https://github.com/ProcessMaker/modeler/blob/cb547141e6632bb5fbdd07d65433b13ca0a8fbd7/src/components/modeler/Modeler.vue#L597

The computed properties in `crownConfig.vue` related to the node are the following:
https://github.com/ProcessMaker/modeler/blob/cb547141e6632bb5fbdd07d65433b13ca0a8fbd7/src/components/crown/crownConfig/crownConfig.vue#L114-L122

I think a good approach to move this forward would be to create a `Node` class (maybe using a more unique name, since node is fairly generic), with the above referenced properties.

Having the class in place would then open up more opportunities for refactor, such as moving some of the functionality in `nodeManager.js` into our node class.

**Comment by chipit24** [comment]
This issue was resolved in https://github.com/ProcessMaker/modeler/pull/1009.
