### ISSUE TITLE
Configuration Accordion 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/modeler#898]
There seems to be an inconsistency in how the "Configuration" accordion behaves when a BPMN element is initially placed into the Process model: sometimes the "Configuration" panel is expanded by default, other times not.

Also when one selects an accordion, that accordion expands while any expanded accordion collapses.  Only one accordion can be open at a time.

**Comment by JCook21** [comment]
@velkymx for the first point, can you be more specific about which elements behave differently when placed onto the paper? I just checked with every element that we have and I didn't see this behaviour. I was running in standalone though and that maybe the difference.

For the second point, this seems to be by design rather than a bug. We can look into it though. Can you describe exactly what you're looking for? Should it be possible to have an unlimited number of accordions open at the same time?

**Comment by velkymx** [comment]
I'm seeing multiple accordions open at once on focus - such as the Intermediate Timer Events

![image](https://user-images.githubusercontent.com/535300/70261539-82098400-1747-11ea-89b3-a630f2c54dce.png)


For the 2nd point - I'm seeing it on develop.

1. Drag a task onto the canvas
2. Click on the Advanced Accordion

Notice how the Configuration Accordion does not close. Only one accordion should be expanded at a time.
